<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="RetryFailedTests" duration-ms="124065" started-at="2018-09-27T11:34:00Z" finished-at="2018-09-27T11:36:04Z">
    <groups>
    </groups>
    <test name="RetryMulitple" duration-ms="124065" started-at="2018-09-27T11:34:00Z" finished-at="2018-09-27T11:36:04Z">
      <class name="reTryMechanism.LoginPage">
        <test-method status="PASS" signature="setUP()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="setUP" is-config="true" duration-ms="199" started-at="2018-09-27T11:34:00Z" finished-at="2018-09-27T11:34:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="PASS" signature="navigateApp()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="navigateApp" is-config="true" duration-ms="9268" started-at="2018-09-27T11:34:00Z" finished-at="2018-09-27T11:34:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method status="SKIP" signature="extentFail()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="extentFail" duration-ms="18" started-at="2018-09-27T11:34:10Z" finished-at="2018-09-27T11:34:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed Test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at reTryMechanism.LoginPage.extentFail(LoginPage.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentFail -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="closeDriver" is-config="true" duration-ms="1744" started-at="2018-09-27T11:34:10Z" finished-at="2018-09-27T11:34:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="navigateApp()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="navigateApp" is-config="true" duration-ms="7714" started-at="2018-09-27T11:34:11Z" finished-at="2018-09-27T11:34:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method status="SKIP" signature="extentFail()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="extentFail" duration-ms="1" started-at="2018-09-27T11:34:19Z" finished-at="2018-09-27T11:34:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed Test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at reTryMechanism.LoginPage.extentFail(LoginPage.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentFail -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="closeDriver" is-config="true" duration-ms="603" started-at="2018-09-27T11:34:19Z" finished-at="2018-09-27T11:34:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="navigateApp()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="navigateApp" is-config="true" duration-ms="5634" started-at="2018-09-27T11:34:20Z" finished-at="2018-09-27T11:34:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method status="FAIL" signature="extentFail()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="extentFail" duration-ms="2" started-at="2018-09-27T11:34:25Z" finished-at="2018-09-27T11:34:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed Test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at reTryMechanism.LoginPage.extentFail(LoginPage.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentFail -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="closeDriver" is-config="true" duration-ms="605" started-at="2018-09-27T11:34:25Z" finished-at="2018-09-27T11:34:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="navigateApp()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="navigateApp" is-config="true" duration-ms="8767" started-at="2018-09-27T11:34:26Z" finished-at="2018-09-27T11:34:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method status="SKIP" signature="verifyLogin()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="verifyLogin" duration-ms="8533" started-at="2018-09-27T11:34:35Z" finished-at="2018-09-27T11:34:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at reTryMechanism.LoginPage.verifyLogin(LoginPage.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="closeDriver" is-config="true" duration-ms="626" started-at="2018-09-27T11:34:43Z" finished-at="2018-09-27T11:34:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="navigateApp()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="navigateApp" is-config="true" duration-ms="5781" started-at="2018-09-27T11:34:44Z" finished-at="2018-09-27T11:34:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method status="PASS" signature="verifyLogin()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="verifyLogin" duration-ms="65392" started-at="2018-09-27T11:34:50Z" finished-at="2018-09-27T11:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="closeDriver" is-config="true" duration-ms="654" started-at="2018-09-27T11:35:55Z" finished-at="2018-09-27T11:35:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="navigateApp()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="navigateApp" is-config="true" duration-ms="7230" started-at="2018-09-27T11:35:56Z" finished-at="2018-09-27T11:36:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateApp -->
        <test-method status="PASS" signature="verifyLoginPage()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="verifyLoginPage" duration-ms="636" started-at="2018-09-27T11:36:03Z" finished-at="2018-09-27T11:36:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPage -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:reTryMechanism.LoginPage@34c4973]" name="closeDriver" is-config="true" duration-ms="615" started-at="2018-09-27T11:36:03Z" finished-at="2018-09-27T11:36:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- reTryMechanism.LoginPage -->
    </test> <!-- RetryMulitple -->
  </suite> <!-- RetryFailedTests -->
</testng-results>
