<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="LAPTOP-AP49OGSV" name="reTryMechanism.LoginPage" tests="6" failures="1" timestamp="27 Sep 2018 11:36:04 GMT" time="123.823" errors="0">
  <testcase name="verifyLogin" time="71.629" classname="reTryMechanism.LoginPage"/>
  <testcase name="extentFail" time="6.388" classname="reTryMechanism.LoginPage">
    <failure type="java.lang.AssertionError" message="Failed Test expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failed Test expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at reTryMechanism.LoginPage.extentFail(LoginPage.java:90)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- extentFail -->
  <testcase name="extentFail" time="7.885" classname="reTryMechanism.LoginPage">
    <skipped/>
  </testcase> <!-- extentFail -->
  <testcase name="extentFail" time="10.529" classname="reTryMechanism.LoginPage">
    <skipped/>
  </testcase> <!-- extentFail -->
  <testcase name="verifyLogin" time="16.873" classname="reTryMechanism.LoginPage">
    <skipped/>
  </testcase> <!-- verifyLogin -->
  <testcase name="verifyLoginPage" time="10.519" classname="reTryMechanism.LoginPage"/>
</testsuite> <!-- reTryMechanism.LoginPage -->
